package logger

var RECORDING_STOP_ERR string = "Recording failed to stop"
var RECORDING_START_ERR string = "Recording failed to start"
var RECORDING_PROCESS_ERR string = "Recording failed to process"
var RECORDING_UPDATE_ERR string = "failed to update Recording"
var RECORDING_CREATE_ERR string = "failed to create Recording"
var CALL_UPDATE_ERR string = "Failed to update call record"
var CALL_CREATE_ERR string = "Failed to create call record"
var STT_ERR string = "Failed to stop text to speech"
var MEDIA_PLAYBACK_ERR string = "Failed to playback media"
var MACRO_RUNTIME_ERR string = "Failed to process macro"
var SEND_DIGITS_ERR string = "Failed to process send digits"
var WAIT_ERR string = "Failed to process wait"
var SET_VARIABLES_ERR string = "Failed to process macro"
var SWITCH_ERR string = "Failed to process switch node"
var PLAYBACK_DOWNLOAD_ERR string = "Failed to download playback file"
var FLOW_RUNTIME_ERR string = "Failed to process flow"
var BRIDGE_ERR string = "Bridge error occured"
var CHANNEL_ERR string = "Channel error occured"
var DOMAIN_LOOKUP_ERR string = "Channel error occured"
var FREE_TRIAL_ENDED string = "free trial expired cannot complete call."
var FAX_RECEIVE_ERR string = "could not receive fax.."
var OUTBOUND_CALL_MACRO string = "could not call due to outbound call macro"